### PR TITLE
Add Discord integration

### PR DESCRIPTION
**Pull request by vicnicius**
Hi! 👋 

Adding Discord as a new source. Discord is somewhat limited in its webhook (they're officially called interaction endpoints) capabilities. It's not possible to create or manipulate them via an API, nor it's possible to subscribe to specific events. It will all depend on your application capabilities.

Because of that, most of the methods in the integration class are no-ops or just return dumb data. I tried to follow the patterns on the other Integrations where possible, but of course, let me know if we should deal with any of them differently.

I'll add all the info regarding the API and the integration in a follow-up PR (or this one) as soon as I get an 👍 for the code.

### CODE REVIEW

**Comment by moekatib** [comment]
Hey 👋🏻

Thanks for the PR. Couldn't we use this https://discord.com/developers/docs/resources/webhook#create-webhook for programatic creation? We can use the channel as part of the init variable if that is possible.

**Comment by moekatib** [comment]
On another look it seems that what they refer to as webhook is not an actual webhook, right?

**Comment by vicnicius** [comment]
> Hey 👋🏻
> 
> Thanks for the PR. Couldn't we use this https://discord.com/developers/docs/resources/webhook#create-webhook for programatic creation? We can use the channel as part of the init variable if that is possible. Or this for something else?

Hi @moekatib! This is something else. Those webhooks sit on your Discord server so you can push messages to it more easily. So it's kind of the opposite way. This is the section where they explain how to receive messages: https://discord.com/developers/docs/interactions/receiving-and-responding#receiving-an-interaction

**Comment by moekatib** [comment]
Discord's current system is not compatible with Buildable for this time.

**Pull request closed without merging**
